### 전체 Feature Flag 조회
GET http://localhost:8080/api/v1/feature-flag/list


### Feature Flag 생성
POST http://localhost:8080/api/v1/feature-flag/create
Content-Type: application/json

{
    "name": "registerMember-v1.0"
}

### Feature Flag 활성/비활성화
PATCH http://localhost:8080/api/v1/feature-flag/modify/active/{{id}}
Content-Type: application/json


### Feature Flag 삭제
DELETE http://localhost:8080/api/v1/feature-flag/delete/{{id}}
Content-Type: application/json
